<?php

/**
 * @file
 * Primary module hooks for Deptagency User Auth Token module.
 */

use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_ENTITY_TYPE_create().
 */
function deptagency_user_auth_token_user_create(EntityInterface $entity) {
  /** @var \Drupal\user\UserInterface $entity */
  if (!$entity->hasField('auth_token')) {
    return;
  }

  /** @var \Drupal\deptagency_user_auth_token\Processor $processor */
  $processor = \Drupal::service('deptagency_user_auth_token.processor');

  $entity->set('auth_token', $processor->generateAuthToken());
}
